[package]
name = "oslog"
description = "A minimal safe wrapper around Apple's Logging system"
repository = "https://github.com/steven-joruk/oslog"
version = "0.3.0"
authors = ["Steven Joruk <steven@joruk.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["logging", "macos", "apple", "oslog"]
categories = ["development-tools::debugging"]

[workspace]
members = [".", "oslog-macros"]

[dependencies]
oslog-macros = { path = "oslog-macros", version = "0.3.0" }
